
environment:
  matrix:
      - PYTHON_VERSION: "3.6"
        MINICONDA: "C:\\Miniconda36-x64"
        PYTHON_ARCH: "64"
      - PYTHON_VERSION: "3.7"
        MINICONDA: "C:\\Miniconda37-x64"
        PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # these correspond to folder naming of miniconda installs on appveyor.  See
  # https://www.appveyor.com/docs/installed-software#python
  - if "%PYTHON_VERSION%" == "3.6" set "BASE_PYTHON_VERSION=36"
  - if "%PYTHON_ARCH%" == "64" set "ARCH_LABEL=-x64"
  # These are already installed on appveyor.  Update them.
  - set "CONDA_ROOT=C:\Miniconda%BASE_PYTHON_VERSION%%ARCH_LABEL%"
  - set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"

  # create conda environment
  - conda update --yes conda
  - conda create -n testing python="%PYTHON_VERSION%" --yes
  - conda --version
  - activate testing
  - conda install -y numpy pandas pyyaml xlrd xlsxwriter matplotlib==3.0.3 seaborn==0.9.0 six requests jupyter nbconvert proj4==5.2.0 pywin32
  - conda install -y -c conda-forge libiconv gdal fiona "geopandas<0.5.0" cartopy cython pyproj==1.9.6

build: false

test_script:
  - conda list
  - pip install -e .[tests,deploy]
  - pytest -v --mpl tests --mpl-results-path=test-artifacts

artifacts:
  - path: 'test-artifacts\*\*'
    name: test-artifacts

on_failure:
  - dir test-artifacts /s /b /o:gn
  - ps: Get-ChildItem test-artifacts\*\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

on_success:
  - echo Build succesful!
