name: publish

on:
  push:
    # build the package on any push to a release-candidate branch
    branches: [ "release/rc_v*" ]
    # deploy to test-pypi on any push of a version tag
    tags: [ "v*" ]
  release:
    # deploy to pypi when publishing a new release
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: publish-${{ runner.os }}

    - name: Upgrade pip, wheel, setuptools-scm
      run: python -m pip install --upgrade pip wheel setuptools-scm twine

    - name: Build package
      run: |
        python3 setup.py bdist_wheel sdist
        twine check dist/*

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        user: __token__
        password: ${{ secrets.TESTPYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      if: github.event_name == 'release'
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
