name: publish

on:
  push:
    # build the package on any push to a release-candidate branch
    branches: [ "release/rc_v*" ]
    # deploy to test-pypi on any push of a version tag
    tags: [ "v*" ]
  release:
    # deploy to pypi when publishing a new release
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5

    #------------------------------
    #  install & configure poetry  
    #------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install poetry dynamic versioning plugin
      run: poetry self add "poetry-dynamic-versioning[plugin]"
    - name: Build package
      run: poetry build

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        user: __token__
        password: ${{ secrets.TESTPYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      if: github.event_name == 'release'
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
