# This workflow runs the tests with the oldest explicitly supported versions of dependencies
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest-legacy

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]

jobs:
  pytest-legacy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7.13'

    - name: Install specific out-dated version of dependencies
      # Update the package requirements when changing minimum dependency versions
      # Please also add a section "Dependency changes" to the release notes
      run: pip install pandas==1.2.0 numpy==1.19.0 matplotlib==3.5.0 iam-units==2020.4.21 xlrd==2.0 pint==0.13

    - name: Install other dependencies and package
      run: pip install .[tests,optional_plotting,optional_io_formats,tutorials]

    - name: Test with pytest
      run: pytest tests
